import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../../core/services/showroom_management_service.dart';
import 'showroom_form_state.dart';

/// Cubit managing showroom creation, editing, and statutory validations
class ShowroomFormCubit extends Cubit<ShowroomFormState> {
  final ShowroomManagementService _service;

  ShowroomFormCubit({ShowroomManagementService? service})
      : _service = service ?? ShowroomManagementService.instance,
        super(const ShowroomFormInitial());

  static final RegExp gstinRegex =
      RegExp(r'^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$');
  static final RegExp panRegex = RegExp(r'^[A-Z]{5}[0-9]{4}[A-Z]{1}$');
  static final RegExp ifscRegex = RegExp(r'^[A-Z]{4}0[A-Z0-9]{6}$');
  static final RegExp pincodeRegex = RegExp(r'^[1-9][0-9]{5}$');

  /// Initialize form for creating a new showroom
  void initNewShowroom() {
    emit(const ShowroomFormReady(
      existingShowroom: null,
      availableStates: ShowroomManagementService.indianStatesAndUTs,
    ));
  }

  /// Load existing showroom for editing
  Future<void> loadShowroomForEdit(String showroomId) async {
    emit(const ShowroomFormLoading());
    try {
      final showroom = await _service.fetchShowroomById(showroomId);
      if (showroom == null) {
        emit(const ShowroomFormError('Showroom not found'));
        return;
      }

      emit(ShowroomFormReady(
        existingShowroom: showroom,
        availableStates: ShowroomManagementService.indianStatesAndUTs,
      ));
    } catch (e) {
      emit(ShowroomFormError(e.toString().replaceFirst('Exception: ', '')));
    }
  }

  /// Save showroom (create or update)
  Future<void> saveShowroom({
    required String name,
    required String code,
    required String address,
    required String city,
    required String state,
    required String pincode,
    required String phone,
    String? email,
    String? gstin,
    String? pan,
    String? bankName,
    String? bankAccountNumber,
    String? bankIfsc,
    String? bankBranch,
    required String invoicePrefix,
    bool isActive = true,
  }) async {
    if (this.state is! ShowroomFormReady) return;

    final formState = this.state as ShowroomFormReady;

    // Validate GSTIN if present
    final cleanGstin = gstin?.trim().toUpperCase();
    if (cleanGstin != null && cleanGstin.isNotEmpty && !gstinRegex.hasMatch(cleanGstin)) {
      emit(const ShowroomFormError('Invalid GSTIN format (15 characters required, e.g. 27AABCU9603R1ZM)'));
      emit(formState);
      return;
    }

    // Validate PAN if present
    final cleanPan = pan?.trim().toUpperCase();
    if (cleanPan != null && cleanPan.isNotEmpty && !panRegex.hasMatch(cleanPan)) {
      emit(const ShowroomFormError('Invalid PAN format (10 characters required, e.g. AABCU9603R)'));
      emit(formState);
      return;
    }

    // Validate IFSC if present
    final cleanIfsc = bankIfsc?.trim().toUpperCase();
    if (cleanIfsc != null && cleanIfsc.isNotEmpty && !ifscRegex.hasMatch(cleanIfsc)) {
      emit(const ShowroomFormError('Invalid IFSC code format (e.g. HDFC0000042)'));
      emit(formState);
      return;
    }

    // Validate Pincode
    final cleanPincode = pincode.trim();
    if (!pincodeRegex.hasMatch(cleanPincode)) {
      emit(const ShowroomFormError('Invalid 6-digit Indian PIN code'));
      emit(formState);
      return;
    }

    emit(const ShowroomFormSaving());

    try {
      final now = DateTime.now();

      if (formState.isEditMode) {
        final existing = formState.existingShowroom!;
        final updatedEntity = ShowroomEntity(
          id: existing.id,
          name: name.trim(),
          code: code.trim().toUpperCase(),
          address: address.trim(),
          city: city.trim(),
          state: state.trim(),
          pincode: cleanPincode,
          phone: phone.trim(),
          email: email?.trim(),
          gstin: cleanGstin,
          pan: cleanPan,
          bankName: bankName?.trim(),
          bankAccountNumber: bankAccountNumber?.trim(),
          bankIfsc: cleanIfsc,
          bankBranch: bankBranch?.trim(),
          invoicePrefix: invoicePrefix.trim().toUpperCase(),
          isActive: isActive,
          createdAt: existing.createdAt,
          updatedAt: now,
        );

        final result = await _service.updateShowroom(updatedEntity);
        emit(ShowroomFormSuccess('Showroom updated successfully', result));
      } else {
        final newEntity = ShowroomEntity(
          id: '', // Generated by service / DB
          name: name.trim(),
          code: code.trim().toUpperCase(),
          address: address.trim(),
          city: city.trim(),
          state: state.trim(),
          pincode: cleanPincode,
          phone: phone.trim(),
          email: email?.trim(),
          gstin: cleanGstin,
          pan: cleanPan,
          bankName: bankName?.trim(),
          bankAccountNumber: bankAccountNumber?.trim(),
          bankIfsc: cleanIfsc,
          bankBranch: bankBranch?.trim(),
          invoicePrefix: invoicePrefix.trim().toUpperCase(),
          isActive: isActive,
          createdAt: now,
          updatedAt: now,
        );

        final result = await _service.createShowroom(newEntity);
        emit(ShowroomFormSuccess('Showroom created successfully with document sequences', result));
      }
    } catch (e) {
      emit(ShowroomFormError(e.toString().replaceFirst('Exception: ', '')));
      emit(formState);
    }
  }
}
